### ISSUE TITLE
error in numpy/ list multiplication inside mutate_smi_list

### ISSUE THREAD

**Issue by sofroniewn** [aspuru-guzik-group/JANUS#9]
Hello, I am trying to run the provided example, but get the following error

```python-traceback
$ python ./example.py
    Unique and valid fragments generated: 107308
    Unique and valid fragments generated: 107308
On generation 0/200
/Users/nsofroniew/opt/anaconda3/envs/chem/lib/python3.9/site-packages/janus/janus.py:457: RuntimeWarning: overflow encountered in power
  prob_ = 1.0 / (3.0 ** ((F_50_val - fitness) / (F_50_val - F_25_val)) + 1)
    (Explr) Top Fitness: 15.811199999999957
    (Explr) Top Smile: CCCCCCCCCCCCCCCCOP(=O)(O)Oc1ccc(C=Cc2ccc(OP(=O)(O)OCCCCCCCCCCCCCCCC)cc2)cc1
Traceback (most recent call last):
  File "/Users/nsofroniew/Documents/code/chem/janus/tests/./example.py", line 81, in <module>
  File "/Users/nsofroniew/opt/anaconda3/envs/chem/lib/python3.9/site-packages/janus/janus.py", line 317, in run
    mut_smi_loc = self.mutate_smi_list(smiles_local_search, "local")
  File "/Users/nsofroniew/opt/anaconda3/envs/chem/lib/python3.9/site-packages/janus/janus.py", line 137, in mutate_smi_list
    smi_list = smi_list * num_random_samples
numpy.core._exceptions._UFuncNoLoopError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U98'), dtype('int64')) -> None
```

It looks like `smi_list` has become a numpy array, which is unintended and it should be a list. This can be fixed by making this line https://github.com/aspuru-guzik-group/JANUS/blob/a52e5994a108063e3fc1d692752cea0ff0240120/src/janus/janus.py#L137 be

```python
    smi_list = list(smi_list) * num_random_samples
```

There could be other, more desirable fixes that avoid this problem altogether. I am happy to submit a PR if this fix is desired though.

**Comment by sofroniewn** [comment]
Looks like the array in question might come from https://github.com/aspuru-guzik-group/JANUS/blob/a52e5994a108063e3fc1d692752cea0ff0240120/src/janus/janus.py#L294

**Comment by gkwt** [comment]
Thanks for reporting this issue. It will be fixed in the next push!
